name: Deploy to prod
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - configs/prod/**/*.json

jobs:
  deploy:
    name: Deploy prod configmap
    uses: ./.github/workflows/deploy-configmap.yml
    permissions:
      contents: "read"
      id-token: "write"
    with:
      env: prod