name: Deploy to prod
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy prod configmap
    uses: ./.github/workflows/deploy-configmap.yml
    permissions:
      contents: read
      id-token: write
    with:
      env: prod

  release:
    name: Create a new release
    needs: deploy
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
      - name: Generate unique tag name
        run: echo "TAG_NAME=$(date +%s)" >> $GITHUB_ENV
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          target_commitish: main
          tag_name: release/prod@${{ env.TAG_NAME }} # Generates a unique tag using timestamp
          name: Release ${{ github.ref_name }}
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }} # This is a PAT with repo permissions
